<?php
	define('ROOT','http://localhost/booksbhandar/',true);
	define('CSS',ROOT.'css/',true);
	define('JS',ROOT.'js/',true);
	define('HOSTNAME','localhost',true);
	define('USERNAME','root',true);
	define('PASSWORD','',true);
	define('DB','booksbhandar',true);
?>